package entity;
// Generated May 16, 2019 1:40:28 PM by Hibernate Tools 4.3.1



/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer id;
     private String kategori;
     private String jenis;
     private String harga;

    public Menu() {
    }

    public Menu(String kategori, String jenis, String harga) {
       this.kategori = kategori;
       this.jenis = jenis;
       this.harga = harga;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getKategori() {
        return this.kategori;
    }
    
    public void setKategori(String kategori) {
        this.kategori = kategori;
    }
    public String getJenis() {
        return this.jenis;
    }
    
    public void setJenis(String jenis) {
        this.jenis = jenis;
    }
    public String getHarga() {
        return this.harga;
    }
    
    public void setHarga(String harga) {
        this.harga = harga;
    }




}


